[package]
name = "storykeep-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "migrate"] }
tokio = { version = "1.53.2", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
warp = { version = "0.4.3", features = ["server"] }
